import unittest
import num_to_words


class TestNumToWords(unittest.TestCase):
    cases = [
        (0, 'zero'),
        (539, 'five hundred and thirty-nine'),
        (9121, 'nine thousand, one hundred and twenty-one'),
        (234569, "two hundred and thirty-four thousand, five hundred and sixty-nine"),
        (10022, 'ten thousand and twenty-two'),
        (66723107008,
         'sixty-six billion, seven hundred and twenty-three million, one hundred and seven thousand and eight'),
        (1, 'one'),
        (10, 'ten'),
        (11, 'eleven'),
        (100, 'one hundred'),
        (101, 'one hundred and one'),
        (110, 'one hundred and ten'),
        (-536, 'minus five hundred and thirty-six'),
        (1000, 'one thousand'),
        (1001, 'one thousand and one'),
        (1010, 'one thousand and ten'),
        (1100, 'one thousand, one hundred'),
        (1101, 'one thousand, one hundred and one'),
        (1190, 'one thousand, one hundred and ninety'),
        (10000, "ten thousand"),
        (10001, "ten thousand and one"),
        (10010, "ten thousand and ten"),
        (10100, "ten thousand, one hundred"),
        (10101, "ten thousand, one hundred and one"),
        (10110, "ten thousand, one hundred and ten"),
        (100000, "one hundred thousand"),
        (100001, "one hundred thousand and one"),
        (100010, "one hundred thousand and ten"),
        (100100, "one hundred thousand, one hundred"),
        (100101, "one hundred thousand, one hundred and one"),
        (100110, "one hundred thousand, one hundred and ten"),
        (101000, "one hundred and one thousand"),
        (101001, "one hundred and one thousand and one"),
        (101010, "one hundred and one thousand and ten"),
        (101100, "one hundred and one thousand, one hundred"),
        (101101, 'one hundred and one thousand, one hundred and one'),
        (110000, "one hundred and ten thousand"),
        (110001, "one hundred and ten thousand and one"),
        (110100, "one hundred and ten thousand, one hundred"),
        (110101, "one hundred and ten thousand, one hundred and one"),
        (110110, "one hundred and ten thousand, one hundred and ten"),
        (110111, "one hundred and ten thousand, one hundred and eleven"),
        (111000, "one hundred and eleven thousand"),
        (111001, "one hundred and eleven thousand and one"),
        (111010, "one hundred and eleven thousand and ten"),
        (111011, "one hundred and eleven thousand and eleven"),
        (111100, "one hundred and eleven thousand, one hundred"),
        (111101, "one hundred and eleven thousand, one hundred and one"),
        (111110, "one hundred and eleven thousand, one hundred and ten"),
        (111111, "one hundred and eleven thousand, one hundred and eleven"),
        (1000000, "one million"),
        (1000001, "one million and one"),
        (1000010, "one million and ten"),
        (1000011, "one million and eleven"),
        (1000100, "one million, one hundred"),
        (1000101, "one million, one hundred and one"),
        (1000110, "one million, one hundred and ten"),
        (1000111, "one million, one hundred and eleven"),
        (1001000, "one million and one thousand"),
        (1001001, "one million and one thousand and one"),
        (1001010, "one million and one thousand and ten"),
        (1001011, "one million and one thousand and eleven"),
        (1001100, "one million and one thousand, one hundred"),
        (1001101, "one million and one thousand, one hundred and one"),
        (1001110, "one million and one thousand, one hundred and ten"),
        (1001111, "one million and one thousand, one hundred and eleven"),
        (1010000, "one million and ten thousand"),
        (1010001, "one million and ten thousand and one"),
        (1010010, "one million and ten thousand and ten"),
        (1010011, "one million and ten thousand and eleven"),
        (1010100, "one million and ten thousand, one hundred"),
        (1010101, "one million and ten thousand, one hundred and one"),
        (1010110, "one million and ten thousand, one hundred and ten"),
        (1010111, "one million and ten thousand, one hundred and eleven"),
        (1011000, "one million and eleven thousand"),
        (1011001, "one million and eleven thousand and one"),
        (1011010, "one million and eleven thousand and ten"),
        (1011011, "one million and eleven thousand and eleven"),
        (1011100, "one million and eleven thousand, one hundred"),
        (1011101, "one million and eleven thousand, one hundred and one"),
        (1011110, "one million and eleven thousand, one hundred and ten"),
        (1011111, "one million and eleven thousand, one hundred and eleven"),
        (1100000, "one million, one hundred thousand"),
        (1100001, "one million, one hundred thousand and one"),
        (1100010, "one million, one hundred thousand and ten"),
        (1100011, "one million, one hundred thousand and eleven"),
        (1100100, "one million, one hundred thousand, one hundred"),
        (1100101, "one million, one hundred thousand, one hundred and one"),
        (1100110, "one million, one hundred thousand, one hundred and ten"),
        (1100111, "one million, one hundred thousand, one hundred and eleven"),
        (1101000, "one million, one hundred and one thousand"),
        (1101001, "one million, one hundred and one thousand and one"),
        (1101010, "one million, one hundred and one thousand and ten"),
        (1101011, "one million, one hundred and one thousand and eleven"),
        (1101100, "one million, one hundred and one thousand, one hundred"),
        (1101101, "one million, one hundred and one thousand, one hundred and one"),
        (1101110, "one million, one hundred and one thousand, one hundred and ten"),
        (1101111, "one million, one hundred and one thousand, one hundred and eleven"),
        (1110000, "one million, one hundred and ten thousand"),
        (1110001, "one million, one hundred and ten thousand and one"),
        (1110010, "one million, one hundred and ten thousand and ten"),
        (1110011, "one million, one hundred and ten thousand and eleven"),
        (1110100, "one million, one hundred and ten thousand, one hundred"),
        (1110101, "one million, one hundred and ten thousand, one hundred and one"),
        (1110110, "one million, one hundred and ten thousand, one hundred and ten"),
        (1110111, "one million, one hundred and ten thousand, one hundred and eleven"),
        (1111000, "one million, one hundred and eleven thousand"),
        (1111001, "one million, one hundred and eleven thousand and one"),
        (1111010, "one million, one hundred and eleven thousand and ten"),
        (1111011, "one million, one hundred and eleven thousand and eleven"),
        (1111100, "one million, one hundred and eleven thousand, one hundred"),
        (1111101, "one million, one hundred and eleven thousand, one hundred and one"),
        (1111110, "one million, one hundred and eleven thousand, one hundred and ten"),
        (1111111, "one million, one hundred and eleven thousand, one hundred and eleven"),
        (10000000, "ten million"),
        (10000001, "ten million and one"),
        (10000010, "ten million and ten"),
        (10000011, "ten million and eleven"),
        (10000100, "ten million, one hundred"),
        (10000101, "ten million, one hundred and one"),
        (10000110, "ten million, one hundred and ten"),
        (10000111, "ten million, one hundred and eleven"),
        (10001000, "ten million and one thousand"),
        (10001001, "ten million and one thousand and one"),
        (10001010, "ten million and one thousand and ten"),
        (10001011, "ten million and one thousand and eleven"),
        (10001100, "ten million and one thousand, one hundred"),
        (10001101, "ten million and one thousand, one hundred and one"),
        (10001110, "ten million and one thousand, one hundred and ten"),
        (10001111, "ten million and one thousand, one hundred and eleven"),
        (10010000, "ten million and ten thousand"),
        (10010001, "ten million and ten thousand and one"),
        (10010010, "ten million and ten thousand and ten"),
        (10010011, "ten million and ten thousand and eleven"),
        (10010100, "ten million and ten thousand, one hundred"),
        (10010101, "ten million and ten thousand, one hundred and one"),
        (10010110, "ten million and ten thousand, one hundred and ten"),
        (10010111, "ten million and ten thousand, one hundred and eleven"),
        (10011000, "ten million and eleven thousand"),
        (10011001, "ten million and eleven thousand and one"),
        (10011010, "ten million and eleven thousand and ten"),
        (10011011, "ten million and eleven thousand and eleven"),
        (10011100, "ten million and eleven thousand, one hundred"),
        (10011101, "ten million and eleven thousand, one hundred and one"),
        (10011110, "ten million and eleven thousand, one hundred and ten"),
        (10011111, "ten million and eleven thousand, one hundred and eleven"),
        (10100000, "ten million, one hundred thousand"),
        (10100001, "ten million, one hundred thousand and one"),
        (10100010, "ten million, one hundred thousand and ten"),
        (10100011, "ten million, one hundred thousand and eleven"),
        (10100100, "ten million, one hundred thousand, one hundred"),
        (10100101, "ten million, one hundred thousand, one hundred and one"),
        (10100110, "ten million, one hundred thousand, one hundred and ten"),
        (10100111, "ten million, one hundred thousand, one hundred and eleven"),
        (10101000, "ten million, one hundred and one thousand"),
        (10101001, "ten million, one hundred and one thousand and one"),
        (10101010, "ten million, one hundred and one thousand and ten"),
        (10101011, "ten million, one hundred and one thousand and eleven"),
        (10101100, "ten million, one hundred and one thousand, one hundred"),
        (10101101, "ten million, one hundred and one thousand, one hundred and one"),
        (10101110, "ten million, one hundred and one thousand, one hundred and ten"),
        (10101111, "ten million, one hundred and one thousand, one hundred and eleven"),
        (10111000, "ten million, one hundred and eleven thousand"),
        (10111001, "ten million, one hundred and eleven thousand and one"),
        (10111010, "ten million, one hundred and eleven thousand and ten"),
        (10111011, "ten million, one hundred and eleven thousand and eleven"),
        (10111100, "ten million, one hundred and eleven thousand, one hundred"),
        (10111101, "ten million, one hundred and eleven thousand, one hundred and one"),
        (10111110, "ten million, one hundred and eleven thousand, one hundred and ten"),
        (10111111, "ten million, one hundred and eleven thousand, one hundred and eleven"),
        (100000000, "one hundred million"),
        (100000001, "one hundred million and one"),
        (100000010, "one hundred million and ten"),
        (100000011, "one hundred million and eleven"),
        (100000100, "one hundred million, one hundred"),
        (100000101, "one hundred million, one hundred and one"),
        (100000110, "one hundred million, one hundred and ten"),
        (100000111, "one hundred million, one hundred and eleven"),
        (111100000, "one hundred and eleven million, one hundred thousand"),
        (111100001, "one hundred and eleven million, one hundred thousand and one"),
        (111100010, "one hundred and eleven million, one hundred thousand and ten"),
        (111100011, "one hundred and eleven million, one hundred thousand and eleven"),
        (111100100, "one hundred and eleven million, one hundred thousand, one hundred"),
        (111110000, "one hundred and eleven million, one hundred and ten thousand"),
        (111110001, "one hundred and eleven million, one hundred and ten thousand and one"),
        (111110010, "one hundred and eleven million, one hundred and ten thousand and ten"),
        (111110011, "one hundred and eleven million, one hundred and ten thousand and eleven"),
        (111110100, "one hundred and eleven million, one hundred and ten thousand, one hundred"),
        (111110101, "one hundred and eleven million, one hundred and ten thousand, one hundred and one"),
        (111110110, "one hundred and eleven million, one hundred and ten thousand, one hundred and ten"),
    ]

    def test_num_2_word(self):
        msg = "expected: \"{}\" got \"{}\" ({})"
        for c, exp in self.cases:
            result = num_to_words.num_2_word(c)
            assert result == exp, msg.format(exp, result, c)

    # edge cases like this were checked with an English teacher about what is the correct way to say large numbers
    # both 'one hundred thousand and one hundred' and below are correct.

    def test_case_special_character(self):
        with self.assertRaises(ValueError):
            num_to_words.sentence_to_num('The barcode is #53009.')

    def test_case_with_units(self):
        with self.assertRaises(ValueError):
            num_to_words.sentence_to_num('The oranges weighed 20064KG')

    def test_check_word_throws_error(self):
        with self.assertRaises(ValueError):
            num_to_words.check_word('#55458')

    def test_check_word_is_valid(self):
        self.assertEqual(True, num_to_words.check_word('35342'))

    def test_check_word_is_invalid(self):
        self.assertEqual(False, num_to_words.check_word('Hello'))


if __name__ == '__main__':
    unittest.main()
